### ISSUE TITLE
Port SecretAttributes

### ISSUE THREAD

**Issue by ancorgs** [ancorgs/y3storage#7]
This includes porting the module `SecretAttributes` and its RSpec testsuite.

The idea is to write a port that is as direct as possible. Do not rethink the whole thing, quite the opposite, putting the source code or the tests side to side should show as few differences as possible.

Only in the future (after having done a direct port of everything) we may consider adapting the code for performance, correctness, etc.

**Comment by jreidinger** [comment]
I will take it, just I cannot assign in your repo.

**Comment by jreidinger** [comment]
fixed with https://github.com/ancorgs/y3storage/pull/8
